#
#   Copyright (c) 2014-2017 Philipp Paulweber
#   All rights reserved.
#
#   Developed by: Philipp Paulweber
#                 Emmanuel Pescosta
#                 https://github.com/ppaulweber/libstdhl
#
#   This file is part of libstdhl.
#
#   libstdhl is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
#   libstdhl is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with libstdhl. If not, see <http://www.gnu.org/licenses/>.
#

language: cpp

matrix:
  include:
    - os: linux
      compiler: clang
      env: 
      addons: &addons_clang_3_8
        apt:
          sources:
            - llvm-toolchain-precise-3.8
          packages:
            - clang-3.8
      before_install:
        - export CXX="clang++-3.8" CC="clang-3.8"
    - os: linux
      compiler: gcc
      env: 
      addons: &addons_gcc_5
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
            - gcc-5
      before_install:
        - export CXX="g++-5" CC="gcc-5"
    - os: linux
      compiler: gcc
      env: 
      addons: &addons_gcc_6
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
            - gcc-6
      before_install:
        - export CXX="g++-6" CC="gcc-6"
  allow_failures:
    - os: osx
      osx_image: xcode8
      compiler: clang
    - os: osx
      osx_image: xcode8
      compiler: gcc

install:
  - |
    echo ${TRAVIS_OS_NAME}
    make  --version
    cmake --version
    ${CC} --version
    ${CXX} --version


script:
  - |
    make debug-all
    make debug-test
    make debug-benchmark
    make sanitize-all
    make sanitize-test
    make sanitize-benchmark
    make release-all
    make release-test
    make release-benchmark
