name: CI

on: [push]

jobs:
  env:
    name: Environment
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v1
    - name: Fetching
      run:  |
        gcc --version
        clang --version
        make --version
        cmake --version
        bash --version

  task:
    name: task
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v1
    - name: Fetching
      run:  make ci-fetch
    - name: Dependencies
      run:  make ci-deps
    - name: Building
      run:  make ci-build
    - name: Tests
      run:  make ci-test
    - name: Benchmark
      run:  make ci-benchmark
    - name: Coverage
      run:  |
        if [ "$C" == "gcc" ]; then
          wget https://codecov.io/bash;
          sh bash -f "!*#usr#include*" 2> /dev/null;
        fi
