name: CI

on: [push]

jobs:
  linux-clang:
    name: Linux Clang
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v1
    - name: Fetching
      run:  make ci-fetch
    - name: Dependencies
      run:  make C=clang debug-deps
    - name: Building
      run:  make C=clang debug
    - name: Tests
      run:  make C=clang debug-test
    - name: Benchmark
      run:  make C=clang debug-benchmark

  linux-gcc:
    name: Linux GCC
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v1
    - name: Fetching
      run:  make ci-fetch
    - name: Dependencies
      run:  make C=gcc coverage-deps
    - name: Building
      run:  make C=gcc coverage
    - name: Tests
      run:  make C=gcc coverage-test
    - name: Benchmark
      run:  make C=gcc coverage-benchmark
    - name: Coverage
      run:  |
        if [ "$C" == "gcc" ]; then
          wget https://codecov.io/bash;
          sh bash -f "!*#usr#include*" 2> /dev/null;
        fi

  darwin-clang:
    name: Darwin Clang
    strategy:
      matrix:
        os: [ macOS-latest ]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v1
    - name: Fetching
      run:  make C=clang ci-fetch
    - name: Dependencies
      run:  make C=clang debug-deps
    - name: Building
      run:  make C=clang debug
    - name: Tests
      run:  make C=clang debug-test
    - name: Benchmark
      run:  make C=clang debug-benchmark

  darwin-gcc:
    name: Darwin GCC
    strategy:
      matrix:
        os: [ macOS-latest ]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v1
    - name: Setup
      run:  |
        brew --version
        brew install gcc
        ln -s /usr/local/bin/gcc-8 /usr/local/bin/gcc
        ln -s /usr/local/bin/g++-8 /usr/local/bin/g++
    - name: Fetching
      run:  make ci-fetch
    - name: Dependencies
      run:  make C=gcc debug-deps
    - name: Building
      run:  make C=gcc debug
    - name: Tests
      run:  make C=gcc debug-test
    - name: Benchmark
      run:  make C=gcc debug-benchmark

  windows-clang:
    name: Windows Clang
    strategy:
      matrix:
        os: [ windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v1
    - name: Setup
      run:  |
        choco install llvm
    - name: Fetching
      run:  make C=clang ci-fetch
    - name: Dependencies
      run:  make C=clang debug-deps
    - name: Building
      run:  make C=clang debug
    - name: Tests
      run:  make C=clang debug-test
    - name: Benchmark
      run:  make C=clang debug-benchmark

  windows-gcc:
    name: Windows GCC
    strategy:
      matrix:
        os: [ windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v1
    - name: Fetching
      run:  make ci-fetch
    - name: Dependencies
      run:  make C=gcc debug-deps
    - name: Building
      run:  make C=gcc debug
    - name: Tests
      run:  make C=gcc debug-test
    - name: Benchmark
      run:  make C=gcc debug-benchmark
