name: CI

on: [push]

jobs:
  linux:
    name: Linux
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    container:
      image: docker://casmlang/container.linux:latest
      volumes:
        - /workspace:/github/workspace
    steps:
    - uses: actions/checkout@v1
    - name: Fetching
      env:
        B: "debug"
        C: "clang"
      run: sh -c make ci-fetch
    - name: Dependencies
      run: sh -c make ci-deps
    - name: Building
      run:  make ci-build
    - name: Tests
      run:  make ci-test
    - name: Benchmark
      run:  make ci-benchmark
    - name: Coverage
      run:  |
        if [ "$C" == "gcc" ]; then
          wget https://codecov.io/bash;
          sh bash -f "!*#usr#include*" 2> /dev/null;
        fi

  darwin:
    name: Darwin
    strategy:
      matrix:
        os: [macOS-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v1
    - name: Setup
      run:  |
        brew --version
        brew install gcc
    - name: Fetching
      env:
        B: "debug"
        C: "clang"
      run:  make ci-fetch
    - name: Dependencies
      run:  make ci-deps
    - name: Building
      run:  make ci-build
    - name: Tests
      run:  make ci-test
    - name: Benchmark
      run:  make ci-benchmark
    - name: Coverage
      run:  |
        if [ "$C" == "gcc" ]; then
          wget https://codecov.io/bash;
          sh bash -f "!*#usr#include*" 2> /dev/null;
        fi

  windows:
    name: Windows
    strategy:
      matrix:
        os: [windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v1
    - name: Fetching
      env:
        B: "debug"
        C: "clang"
      run:  make ci-fetch
    - name: Dependencies
      run:  make ci-deps
    - name: Building
      run:  make ci-build
    - name: Tests
      run:  make ci-test
    - name: Benchmark
      run:  make ci-benchmark
    - name: Coverage
      run:  |
        if [ "$C" == "gcc" ]; then
          wget https://codecov.io/bash;
          sh bash -f "!*#usr#include*" 2> /dev/null;
        fi
